CREATE TABLE IF NOT EXISTS student (
id SERIAL PRIMARY KEY,
surname TEXT NOT NULL,
name TEXT NOT NULL,
patronymic TEXT NOT NULL,
phone_number TEXT NOT NULL UNIQUE,
email TEXT NOT NULL UNIQUE,
telegram TEXT NOT NULL UNIQUE,
git TEXT NOT NULL UNIQUE,
date_birth DATE NOT NULL
);